version: "3"

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
        TZ: 'GMT+3'
        PGTZ: 'GMT+3'
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"